### ISSUE TITLE
upgrade oapi-codegen to v1.13 or higher

### ISSUE THREAD

**Issue by pgier** [datastax/pulsar-admin-client-go#2]
This upgrade is currently blocked due to unnecessary transitive dependencies introduced into v1.13
https://github.com/deepmap/oapi-codegen/issues/1142

Once the upstream issue is fixed, we should upgrade to the latest version.

**Comment by jamietanna** [comment]
Out of interest, why would this be blocking the upgrade? :)

**Comment by pgier** [comment]
@jamietanna I guess it's not necessarily blocked, I just created the issue to remind me that the upgrade needs to be done, and why I didn't do it right away.

**Comment by jamietanna** [comment]
OK that's good to know, thanks!

**Comment by jamietanna** [comment]
@pgier with v1.14.0 / v1.15.0 the impact should be reduced, if you'd mind updating the project. I can't, as it looks like there's no license defined on this project, which means it's proprietary :grin:
